# Site settings
title: Blog Daniel
# email: kkkk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog con fines educativos creado con Jekyll
  Blog para pruebas de la clase de Ingenieria de Software 
  Gracias por su visita.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danielgiraldo88.github.io/" # the base hostname & protocol for your site
twitter_username: danielgiraldo88
github_username:  danielgiraldo88

# Build settings
markdown: kramdown
